function Hd = CH40
%CH40 Returns a discrete-time filter object.

%
% MATLAB Code
% Generated by MATLAB(R) 8.0 and the Signal Processing Toolbox 6.18.
%
% Generated on: 03-Dec-2012 11:28:15
%

% Chebyshev Type II Bandpass filter designed using FDESIGN.BANDPASS.

% All frequency values are in Hz.
Fs = 128;  % Sampling Frequency

N      = 4;   % Order
Fstop1 = 10;  % First Stopband Frequency
Fstop2 = 13;  % Second Stopband Frequency
Astop  = 40;  % Stopband Attenuation (dB)

% Construct an FDESIGN object and call its CHEBY2 method.
h  = fdesign.bandpass('N,Fst1,Fst2,Ast', N, Fstop1, Fstop2, Astop, Fs);
Hd = design(h, 'cheby2');

% [EOF]
